# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: GoatDB Docs
email: contact@goatdb.com
description: >- # this means to ignore newlines until "baseurl:"
  GoatDB - Official Site — Build Your Next Project on GoatDB, the Edge-Native
  Database. GoatDB empowers frontend developers to build and deploy complex,
  scalable, and secure applications in under 20 minutes—without requiring
  backend expertise. It's the fastest and easiest way to create modern apps,
  tailored for today's developer needs.
baseurl: '' # the subpath of your site, e.g. /blog
url: 'https://goatdb.com' # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username: goatplatform

# Build settings
theme: just-the-docs
plugins:
  - jekyll-feed

logo: '/assets/goatdb_logo_dark_500.png'

mermaid:
  version: 11.4.1

# Aux links for the upper right navigation
aux_links:
  'GitHub':
    - '//github.com/goatplatform/goatdb'

# External navigation links
nav_external_links:
  - title: GoatDB on GitHub
    url: https://github.com/goatplatform/goatdb
    hide_icon: false # set to true to hide the external link icon - defaults to false
    opens_in_new_tab: false # set to true to open this link in a new tab - defaults to false

# Google Analytics Tracking (optional)
# Supports a CSV of tracking ID strings (eg. "UA-1234567-89,G-1AB234CDE5")
ga_tracking: G-27ES13ZKRG
ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings (true/nil by default)

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
